### ISSUE TITLE
Fix apiVersion for all Inventory ownerReferences

### ISSUE THREAD

**Issue by damyan** [ironcore-dev/metal#430]
Owner references are created with wrong version:
```  
ownerReferences:
  - apiVersion: v1alpha4
    blockOwnerDeletion: true
    controller: true
    kind: Inventory
    name: f980b0b8-490d-11ea-8cdc-0a94efa938dd
    uid: af574a32-5541-4657-ac65-201a572dce66
```

The apiVersion should be `metal.ironcore.dev/v1alpha4` instead
